namespace EScouting.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateChampions : DbMigration
    {
        public override void Up()
        {
            Sql("SET IDENTITY_INSERT Champions ON");
            Sql("INSERT INTO Champions (Id, Name) VALUES (62, 'Wukong')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (24, 'Jax')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (9, 'Fiddlesticks')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (35, 'Shaco')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (19, 'Warwick')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (498, 'Xayah')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (76, 'Nidalee')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (143, 'Zyra')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (240, 'Kled')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (63, 'Brand')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (33, 'Rummus')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (420, 'Illaoi')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (42, 'Corki')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (201, 'Braum')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (122, 'Darius')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (23, 'Tryndamere')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (21, 'MissFortune')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (83, 'Yorick')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (101, 'Xerath')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (15, 'Sivir')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (92, 'Riven')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (61, 'Orianna')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (41, 'Gangplank')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (54, 'Malphite')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (78, 'Poppy')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (127, 'Lissandra')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (126, 'Jayce')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (20, 'Nunu')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (48, 'Trundle')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (30, 'Karthus')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (104, 'Graves')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (142, 'Zoe')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (150, 'Gnar')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (99, 'Lux')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (102, 'Shyvana')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (58, 'Renekton')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (114, 'Fiora')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (222, 'Jinx')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (429, 'Kalista')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (105, 'Fizz')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (38, 'Kassadin')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (37, 'Sona')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (39, 'Irelia')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (112, 'Viktor')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (497, 'Rakan')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (203, 'Kindred')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (69, 'Cassiopeia')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (57, 'Maokai')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (516, 'Ornn')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (412, 'Thresh')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (10, 'Kayle')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (120, 'Hecarim')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (121, 'Khazix')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (2, 'Olaf')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (115, 'Ziggs')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (134, 'Syndra')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (36, 'DrMundo')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (43, 'Karma')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (1, 'Annie')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (84, 'Akali')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (106, 'Volibear')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (157, 'Yasuo')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (85, 'Kennen')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (107, 'Rengar')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (13, 'Ryze')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (98, 'Shen')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (154, 'Zac')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (91, 'Talon')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (50, 'Swain')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (432, 'Bard')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (14, 'Sion')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (67, 'Vayne')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (75, 'Nasus')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (141, 'Kayn')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (4, 'TwistedFate')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (31, 'Chogath')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (77, 'Udyr')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (236, 'Lucian')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (427, 'Ivern')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (89, 'Leona')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (51, 'Caitlyn')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (113, 'Sejuani')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (56, 'Nocturne')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (26, 'Zilean')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (268, 'Zilean')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (68, 'Rumble')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (25, 'Morgana')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (163, 'Taliyah')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (17, 'Teemo')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (6, 'Urgot')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (32, 'Amumu')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (3, 'Galio')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (74, 'Heimerdinger')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (34, 'Anivia')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (22, 'Ashe')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (161, 'Velkoz')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (27, 'Singed')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (72, 'Singed')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (110, 'Varus')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (29, 'Twitch')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (86, 'Garen')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (53, 'Blitzcrank')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (11, 'MasterYi')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (555, 'Pyke')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (60, 'Elise')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (12, 'Alistar')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (55, 'Katarina')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (245, 'Ekko')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (82, 'Mordekaiser')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (117, 'Lulu')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (164, 'Camille')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (266, 'Aatrox')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (119, 'Draven')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (223, 'TahmKench')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (80, 'Pantheon')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (5, 'XinZhao')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (136, 'AurelionSol')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (64, 'LeeSin')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (44, 'Taric')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (90, 'Malzahar')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (145, 'Kaisa')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (131, 'Diana')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (18, 'Tristana')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (421, 'RekSai')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (8, 'Vladimir')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (59, 'JarvanIV')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (267, 'Nami')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (202, 'Jhin')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (16, 'Soraka')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (45, 'Veigar')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (40, 'Janna')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (111, 'Nautilus')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (28, 'Evelynn')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (79, 'Gragas')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (238, 'Zed')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (254, 'Vi')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (96, 'KogMaw')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (103, 'Ahri')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (133, 'Quinn')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (7, 'Leblanc')");
            Sql("INSERT INTO Champions (Id, Name) VALUES (81, 'Ezreal')");
            Sql("SET IDENTITY_INSERT Champions OFF");
        }
        
        public override void Down()
        {
        }
    }
}
